In [2]:
import numpy as np

In [3]:
# EXERCISE 1 - Element-wise addition of 2 numpy arrays
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])
c = a + b 
c

array([[11, 13, 15],
       [17, 19, 21]])

In [4]:
# EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar
a = np.array([[1,2,3],
              [4,5,6]])
c = a*2
c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
# EXERCISE 3 - Identity Matrix
e = np.identity(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# EXERCISE 4 - Array re-dimensioning
a = np.array([x for x in range(8)])
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
# EXERCISE 5 - Array datatype conversion
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])
a_ = a.astype("int")
a_

array([[2, 3, 1],
       [4, 2, 1]])

In [8]:
# EXERCISE 6 - Obtaining Boolean Array from Binary Array
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

a_ = a.astype("bool")
a_

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [11]:
# EXERCISE 7 - Horizontal Stacking of Numpy Arrays
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

a = np.hstack((a1,a2))
a

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [12]:
# EXERCISE 8 - vertical Stacking of Numpy Arrays
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

a = np.vstack((a1,a2))
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# EXERCISE 9 - Custom Sequence Generation
b = np.array([x for x in range(101) if x%2==0])
b

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
# EXERCISE 10 - from, 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])
c = np.where(a == b)

(array([0, 3, 4], dtype=int64),)

In [20]:
# EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range

a = np.linspace(0,100,5)
print(a)

[  0.  25.  50.  75. 100.]


In [22]:
# EXERCISE 12 - Matrix Generation with one particular value

a = np.full((2,3),5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
# EXERCISE 13 - Array Generation by repeatition of a small array across each dimension
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.tile(a,10)
b

# The Numpy tile() function takes an array, A , and returns the array repeated by a given number of repetitions. 

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
        2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4,
        5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7,
        8, 9, 7, 8, 9, 7, 8, 9]])

In [27]:
# EXERCISE 14 - Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

c = np.random.randint(0,10,(5,5))
c

array([[3, 6, 6, 4, 5],
       [4, 9, 2, 2, 6],
       [3, 9, 4, 8, 4],
       [9, 1, 6, 7, 5],
       [6, 6, 1, 7, 7]])

In [29]:
# EXERCISE 15 - Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
np.matmul(a,b)


array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [30]:
# EXERCISE 16 - Matrix Transpose, Output the transpose of a matrix (as numpy array)
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
# EXERCISE 17 - Sine of an Angle (in radians)
angles = np.array([3.14, 3.14/2, 6.28])

sine_value = np.sin(angles)
sine_value

array([ 0.00159265,  0.99999968, -0.0031853 ])